// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKxFs_YBj4F-hZXl13ZeaMXMmMNyZTXXc',
    appId: '1:4969617579:web:0f7bb2bf5a7b18fbaa3fee',
    messagingSenderId: '4969617579',
    projectId: 'hablar-49ee3',
    authDomain: 'hablar-49ee3.firebaseapp.com',
    storageBucket: 'hablar-49ee3.firebasestorage.app',
    measurementId: 'G-6NNR6LCT99',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0u2s-jH3F3Ni9v661ViUJmnjYcDr7bEc',
    appId: '1:4969617579:android:2c629cb050c80de7aa3fee',
    messagingSenderId: '4969617579',
    projectId: 'hablar-49ee3',
    storageBucket: 'hablar-49ee3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAV1rUJZEw1Zo3WzVOxZ0U7q194KpHEOPg',
    appId: '1:4969617579:ios:0a657a2a1e466b28aa3fee',
    messagingSenderId: '4969617579',
    projectId: 'hablar-49ee3',
    storageBucket: 'hablar-49ee3.firebasestorage.app',
    iosBundleId: 'com.example.hablarClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAV1rUJZEw1Zo3WzVOxZ0U7q194KpHEOPg',
    appId: '1:4969617579:ios:0a657a2a1e466b28aa3fee',
    messagingSenderId: '4969617579',
    projectId: 'hablar-49ee3',
    storageBucket: 'hablar-49ee3.firebasestorage.app',
    iosBundleId: 'com.example.hablarClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKxFs_YBj4F-hZXl13ZeaMXMmMNyZTXXc',
    appId: '1:4969617579:web:ef6c2e007a39ba51aa3fee',
    messagingSenderId: '4969617579',
    projectId: 'hablar-49ee3',
    authDomain: 'hablar-49ee3.firebaseapp.com',
    storageBucket: 'hablar-49ee3.firebasestorage.app',
    measurementId: 'G-7SM1EHFNCK',
  );
}
